.github/workflows/pr-title.yml, README.md
Skipping the jobs completely when running on the merge queue doesn't seem to work when called as a reusable workflow for a required check.
The worker is never started, and the queued job just hangs there.
This PR moves the `if` checks to each step instead, so the general job should now succeed in merge queues.
=> fix(pr-title): Don't skip the whole job on merge queues

.github/workflows/pr-title.yml
The `BREAKING CHANGE` footer check used a different token than the _delete comments_ step, so it wasn't getting deleted after the problem got fixed.
=> ci(pr-title): Fix comments not getting deleted after they get fixed

.github/CODEOWNERS
Adding the main group instead of a subteam. This is a small repo, so we should avoid siloing.
=> chore: Setup CODEOWNERS

.github/workflows/pr-title.yml, README.md
(in addition to the GITHUB_PAT parameter)
Removes the fallback into the implicit GITHUB_TOKEN when no token parameter is given.
Doing that made the workflow always require write access on the runtime token, even if was not used.
=> fix(pr-title): Don't require writeable GITHUB_TOKEN

.github/workflows/add-to-project.yml
Uses the correct path to access the `workflow_call`'s input.
https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#inputs-context
=> fix(add-to-project): Path to input project url

.github/workflows/add-to-project.yml
Reverse case to #10. We were using the local secret instead of reading from the inputs to the workflow -.-'
This should be the last fix...
=> fix(add-to-project): Use input github token

README.md
Unfortunately [`actions/add-to-project`](https://github.com/actions/add-to-project) does not support repos/projects under different organisations. I should probably add an issue.
=> docs: add-to-project requires read permissions on the issues

.github/workflows/rs-semver-checks.yml, README.md
Test PR: https://github.com/CQCL/hugr/pull/1598
Limitations:
- Comments won't be updated when the PR title is changed (added/removed a `!` flag).
It will only change when a new commit is pushed.
=> feat: Rust semver-checks workflow against base branch

.github/workflows/coverage-trend.yml
Now that this gets `workflow_call`ed, we should use the caller's workflow name to look for the previous run stats.
This is the default behaviour of `action-download-artifact` when no workflow name is specified.
Failing run due to mismatched name:
https://github.com/CQCL/hugr/actions/runs/11547150535/job/32136579831
=> fix(coverage-trend): Use the current workflow's name

.github/workflows/pr-title.yml
Post a shorter message when the PR is marked as `RFC:`, reminding the user to change the type before merging.
(The job output will still be a failure, preventing merges).
=> feat(pr-title): Special case when the PR is an RFC

.github/workflows/rs-semver-checks.yml
#22 changed the recommended trigger for the semver checks action to `pull_request_target`, but inside the action we were still checking for `pull_request` targets explicitly so the comments never got posted.
Note that for both events the payload is still called `pull_request`, so there's no need to change the rest of the code.
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
=> fix(semver-checks): Post comments on `pull_request_target`s

.github/workflows/rs-semver-checks.yml
Closes #29 
drive-by: Use the right "head commit" when running in a `pull_request_target` event. Otherwise we where fetching the base ref, and not detecting anything. See [this run](https://github.com/CQCL/hugr/actions/runs/12118219519/job/33782281012?pr=1723#step:2:72), where both HEAD and BASE checkouts use the same sha.
=> feat(rs-semver-checks): Early fail if the crate has build errors

.github/workflows/rs-semver-checks.yml
In #30 I forgot we are checking out the repo to a different directory, so we need to `cd` before running anything -.-'
See failing run due to missing `Cargo.toml`: https://github.com/CQCL/hugr/actions/runs/12118534964/job/33783222406?pr=1723#step:9:15
=> fix(rs-semver-checks): `cd` into checked out repo when `cargo check`ing

.github/workflows/breaking-change-to-main.yml
Variables should be always put into an env var before using them inside bash scripts. Otherwise you may end up [evaluating arbitrary code](https://github.com/CQCL/hugr/actions/runs/14759134813/job/41435128150#step:3:2) 💥
=> fix(breaking-change-to-main): Ensure that env vars are escaped when injecting them into bash

.github/workflows/breaking-change-to-main.yml
Using backticks in `echo` was a bad idea. I don't know why it was working before, but it doesn't work now (it tries to evaluate "main" as a bash command). Bash is great...
=> fix(breaking-change-to-main): No backticks in echo command

.github/workflows/breaking-change-to-main.yml
Makes sure we have a single job to match against as a github pass requirement.
When the check job gets skipped we cannot use it as a required check (since `skipped != successful`), so we need a separate job that succeeds if `skipped || success`.
I also shortened the job names, since the workflow name already has the full description.
=> fix(breaking-main): Define a single fail/no-fail job

.github/workflows/breaking-change-to-main.yml, .github/workflows/pr-title.yml, .github/workflows/rs-semver-checks.yml
Improves the regex that detect the `!` conventional commit flag, so that it detects examples like:
```
fix!: Revert "fix: …
fix!: Revert "fix!: …fix: Revert "fix: …
fix(tag!:)!: Revert "fix: …
fix(tag!:)!: Revert "fix!: …
```
But it does **not** match
```
fix: Revert "fix: …
fix: Revert "fix!: …
fix(tag!:): Revert "fix: …
fix(tag!:): Revert "fix!: …
```
The previous impl matched any `!:` sequence on the title, so it had some false positives.
Regex101 run:
https://regex101.com/r/zD5HRp/1
=> fix: Make the breaking-flag-in-title regex more robust

README.md, py-semver-checks/action.py, py-semver-checks/action.yml, rs-semver-checks/action.yml
- Cleans up both the `rs-semver-checks` and `py-semver-checks`
- Both workflows had invalid attributes that are not allowed in composite actions (leftovers from the port from reusable workflows).
- `py-` inserted `${{...}}` workflow expressions directly into bash scripts. This is a security issue as there is no escaping done on them, replaced them for env variables.
- `py-` wasn't fetching the baseline commit in some cases. This should fix #57 
- Uses [`uv script`s](https://docs.astral.sh/uv/guides/scripts/#running-a-script-with-dependencies) for the `py-` action script, instead of setting up dependencies manually in the workflow.
- Cleans up the README, and removes the legacy reusable workflow example for `rs-`.
=> fix(semver-checks): Fix baseline fetch for python and clear up scripts and docs

py-semver-checks/action.yml
The checker script expects multiple arguments when defining packages, instead of a single space-separated string.
This should fix the error seen on guppylang
https://github.com/CQCL/guppylang/actions/runs/17610099782/job/50029878711?pr=1252#step:7:226
(tested by running the script locally)
=> fix(py-semver-checks): Fix error on multiple py packages

py-semver-checks/action.yml, rs-semver-checks/action.yml
`BASELINE_REV` is defined in multiple places in `py-semver-checks`, but #63 only changed one occurrence.
This PR rolls backs some of those changes.
drive-by: Change the baseline `ref` for its `sha` in `rs-semver-checks` too, since that one seems to behave more correctly... (things are [really underdocumented](https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request) -.-)
=> fix(semver-checks): Mismatched BASELINE sha definitions
